### ISSUE TITLE
hard fault on thread: tcpip

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread-packages/netutils#11]
开发板：正点原子探索者407ZG  RTT:3.0.4  
按照使用说明，点击PUT之后出现
msh />psr: 0x61000000
 pc: 0x08009030
 lr: 0x08009031
r12: 0x00000000
r03: 0x20000208
r02: 0x20000208
r01: 0x2000fa44
r00: 0x00000000
hard fault on thread: tcpip
thread pri  status      sp     stack size max used left tick  error
------ ---  ------- ---------- ----------  ------  ---------- ---
tshell  20  suspend 0x00000140 0x00001000    07%   0x00000006 000
tcpip   10  close   0xfffffd0f 0x0000004b    100%   0x2000f9bf 000
etx     12  ready   0x00000098 0x00000400    14%   0x00000010 000
erx     12  ready   0x000000e0 0x00000400    53%   0x00000010 000
tidle   31  ready   0x00000048 0x00000100    34%   0x0000001c 000

**Comment by armink** [comment]
```
tcpip 10 close 0xfffffd0f 0x0000004b 100% 0x2000f9bf 000
```
tcpip 堆栈爆了，增大下试试？

**Comment by armink** [comment]
@whj4674672 问题已解决？
