### ISSUE TITLE
ntp超时问题

### ISSUE THREAD

**Issue by HubertXie** [RT-Thread-packages/netutils#19]
使用NTP同步网络时间，使用中出现一个问题
系统运行，一直提示 “[E/NTP]: ERROR select the socket timeout(5s)”
但是使用msh命令 ntp_sync立即就能同步时间成功，如图。
![_20180911201454](https://user-images.githubusercontent.com/13606088/45359525-66c0cf00-b5ff-11e8-9b2f-606c87d434c5.png)

**Comment by armink** [comment]
是不是代码执行的太早了，网络还没有连接上

**Comment by HubertXie** [comment]
不是这个问题，在我手动使用质量校时成功后。
后面依然提示这个错误。

**Comment by HubertXie** [comment]
我使用的是sal+at的方式使用WiFi模块接入网络。
现在出现一个新的问题，在ntp多次校时失败后，会出现socket创建失败的现象。
此时其它任务需要创建socket也是提示失败。
打开at_raw日志可以看到，提示失败时，MCU并未向模块发送任何AT指令，应该是系统内部sal部分出错了。

**Comment by HubertXie** [comment]
没有开启lwip
sal的bug找到了，是因为closesocket时处理有问题导致的，我在rtthread项目中提交PR
但是ntp问题还在没找到

**Comment by armink** [comment]
那还是单步看看两个函数执行的区别吧

**Comment by HubertXie** [comment]
msh>ntp_sync
最终也是调用 ntp_sync_to_rtc 来实现的，所以函数内部是没区别的
唯一的区别是在不同的线程中调用。

**Comment by armink** [comment]
再深入单步看下吧，你也说了问题时的 AT 指令都不会发送，这点也是区别

**Comment by HubertXie** [comment]
不发送AT指令是sal的问题，这个已经解决。

**Comment by armink** [comment]
SAL 的什么问题
