### ISSUE TITLE
ntp向三个服务器获取时间，每次都是使用的第一个服务器的IP

### ISSUE THREAD

**Issue by HikerPan** [RT-Thread-packages/netutils#55]
![image](https://user-images.githubusercontent.com/34146874/109408695-d04b1880-79c6-11eb-9467-6a87a5ff403a.png)
见上图，发现每次NTP其实都是使用的第一个服务器dns出来的IP。我看了半天代码，没看出来为什么？
我使用的是AT组件，AT设备是SIM7600，
SIM7600的DNS部分，我跟了代码，发现IP是获取到了。

另外，我发现当获取ntp失败时，堆栈会溢出，当前的1.5K不够用，我是将1.5K乘2以后，发现ntp失败不会死机的。

**Comment by baiqiudi** [comment]
我发现了同样的问题，使用EC20网卡的时候，看代码发现只会跟第一个NTP服务器建立socket连接，多次同步也都是向第一个NTP服务器发送的数据，但是使用以太网就没有问题。

**Comment by yangpengya** [comment]
最新主线已修复[https://github.com/RT-Thread/rt-thread/pull/9403]
