### ISSUE TITLE
希望恢复RTC_SYNC_USING_NTP 配置

### ISSUE THREAD

**Issue by dongly** [RT-Thread-packages/netutils#61]
新版本rt-thread已经删除RTC_SYNC_USING_NTP 配置,可否恢复?

**Comment by mysterywolf** [comment]
你好，新版rt-thread删除NTP部分是因为rtc.c为驱动框架，其只负责提供设置、获取rtc的相关方法，至于是有人来获取/设置还是由机器来获取(NTP)这不是驱动应该负责的问题，因此在最新master中已经从驱动中移除了相关配置。如果你使用最新版的RT-Thread master的话，请使用0.13版本及之后的netutils。该功能不受影响。

**Comment by dongly** [comment]
我已经可用0.13版本的netutils了,但0.13版本也没有RTC_SYNC_USING_NTP 配置选项

**Comment by mysterywolf** [comment]
建议你刷新一下工程以及env，RTC_SYNC_USING_NTP已经删干净了

**Comment by mysterywolf** [comment]
NTP的启动权在netutils这边，直接去nettuils开启NTP就可以看到之前在RTC_SYNC_USING_NTP下的设置了

**Comment by dongly** [comment]
我可能表达得不是很清楚.我是意思是:
* 我要打开 NTP 功能
* 但可以选择是否打开 NTP 同步 RTC (即 `RTC_SYNC_USING_NTP` 选项)

这是的rt-thread V4.03的代码 **有** `RTC_SYNC_USING_NTP` 选项
```c
#ifdef RTC_SYNC_USING_NTP
static void ntp_sync_thread_enrty(void *param)
{
...
}

int rt_rtc_ntp_sync_init(void)
{
   ...
}
INIT_COMPONENT_EXPORT(rt_rtc_ntp_sync_init);
#endif /* RTC_SYNC_USING_NTP */
```

而现在的 netutils 对应的这部分**没有** `RTC_SYNC_USING_NTP` 选项

netutils 的 `Kconfig` 中的 NTP 部分,其中没有 `RTC_SYNC_USING_NTP`
```
    config PKG_NETUTILS_NTP
        bool "Enable NTP(Network Time Protocol) client"
        select RT_USING_SAL
        default n
    if PKG_NETUTILS_NTP
        if PKG_NETUTILS_VER_NUM > 0x10200
            config RTC_NTP_FIRST_SYNC_DELAY
                int "NTP first sync delay time(second) for network connect"
                default 30

            config RTC_NTP_SYNC_PERIOD
                int "NTP auto sync period(second)"
                default 3600
        endif

        if PKG_NETUTILS_VER_NUM <= 0x10200
            config NETUTILS_NTP_TIMEZONE
                int "Timezone for calculate local time"
                range -12 12
                default 8
        endif

        config NETUTILS_NTP_HOSTNAME
            string "NTP server name1"
            default "cn.ntp.org.cn"

        config NETUTILS_NTP_HOSTNAME2
            string "NTP server name2"
            default "ntp.rt-thread.org"

        config NETUTILS_NTP_HOSTNAME3
            string "NTP server name3"
            default "edu.ntp.org.cn"
    endif
```

**Comment by mysterywolf** [comment]
4.0.3版本 请使用0.1.2



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月18日(周二) 上午10:58
收件人: ***@***.***&gt;;
抄送: "Meco Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread-packages/netutils] 希望恢复RTC_SYNC_USING_NTP 配置 (#61)




 
我可能表达得不是很清楚.我是意思是:
  
我要打开 NTP 功能 

但可以选择是否打开 NTP 同步 RTC (即 RTC_SYNC_USING_NTP 选项) 
 
这是的rt-thread V4.03的代码 有 RTC_SYNC_USING_NTP 选项
 #ifdef RTC_SYNC_USING_NTP static void ntp_sync_thread_enrty(void *param) { ... } int rt_rtc_ntp_sync_init(void) {    ... } INIT_COMPONENT_EXPORT(rt_rtc_ntp_sync_init); #endif /* RTC_SYNC_USING_NTP */
 
而现在的 netutils 对应的这部分没有 RTC_SYNC_USING_NTP 选项
 
netutils 的 Kconfig 中的 NTP 部分,其中没有 RTC_SYNC_USING_NTP
     config PKG_NETUTILS_NTP         bool "Enable NTP(Network Time Protocol) client"         select RT_USING_SAL         default n     if PKG_NETUTILS_NTP         if PKG_NETUTILS_VER_NUM &gt; 0x10200             config RTC_NTP_FIRST_SYNC_DELAY                 int "NTP first sync delay time(second) for network connect"                 default 30             config RTC_NTP_SYNC_PERIOD                 int "NTP auto sync period(second)"                 default 3600         endif         if PKG_NETUTILS_VER_NUM <= 0x10200             config NETUTILS_NTP_TIMEZONE                 int "Timezone for calculate local time"                 range -12 12                 default 8         endif         config NETUTILS_NTP_HOSTNAME             string "NTP server name1"             default "cn.ntp.org.cn"         config NETUTILS_NTP_HOSTNAME2             string "NTP server name2"             default "ntp.rt-thread.org"         config NETUTILS_NTP_HOSTNAME3             string "NTP server name3"             default "edu.ntp.org.cn"     endif

**Comment by mysterywolf** [comment]
稍等 明天我会解决这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月18日(周二) 上午10:58
收件人: ***@***.***&gt;;
抄送: "Meco Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread-packages/netutils] 希望恢复RTC_SYNC_USING_NTP 配置 (#61)




 
我可能表达得不是很清楚.我是意思是:
  
我要打开 NTP 功能 

但可以选择是否打开 NTP 同步 RTC (即 RTC_SYNC_USING_NTP 选项) 
 
这是的rt-thread V4.03的代码 有 RTC_SYNC_USING_NTP 选项
 #ifdef RTC_SYNC_USING_NTP static void ntp_sync_thread_enrty(void *param) { ... } int rt_rtc_ntp_sync_init(void) {    ... } INIT_COMPONENT_EXPORT(rt_rtc_ntp_sync_init); #endif /* RTC_SYNC_USING_NTP */
 
而现在的 netutils 对应的这部分没有 RTC_SYNC_USING_NTP 选项
 
netutils 的 Kconfig 中的 NTP 部分,其中没有 RTC_SYNC_USING_NTP
     config PKG_NETUTILS_NTP         bool "Enable NTP(Network Time Protocol) client"         select RT_USING_SAL         default n     if PKG_NETUTILS_NTP         if PKG_NETUTILS_VER_NUM &gt; 0x10200             config RTC_NTP_FIRST_SYNC_DELAY                 int "NTP first sync delay time(second) for network connect"                 default 30             config RTC_NTP_SYNC_PERIOD                 int "NTP auto sync period(second)"                 default 3600         endif         if PKG_NETUTILS_VER_NUM <= 0x10200             config NETUTILS_NTP_TIMEZONE                 int "Timezone for calculate local time"                 range -12 12                 default 8         endif         config NETUTILS_NTP_HOSTNAME             string "NTP server name1"             default "cn.ntp.org.cn"         config NETUTILS_NTP_HOSTNAME2             string "NTP server name2"             default "ntp.rt-thread.org"         config NETUTILS_NTP_HOSTNAME3             string "NTP server name3"             default "edu.ntp.org.cn"     endif

**Comment by dongly** [comment]
是RT-Thread V4.0.4 配 netutils V1.3 无 `RTC_SYNC_USING_NTP` 选项

**Comment by mysterywolf** [comment]
你现在用的是4.0.4还是4.0.3

**Comment by dongly** [comment]
用的是master版本,配 netutils V1.3

**Comment by mysterywolf** [comment]
更新你的master到最新

**Comment by dongly** [comment]
我的rtt已经更新到最新版(5ba96109c60c4b1a66ff),也更新到了lastest版
|                                        项目            |       RTT V4.03  /netutils V1.2          | RTT master/netutils V1.3  |
|--------------------------------------|---------------|------------|
|`ntp_sync_thread_enrty()` 代码所在位置| rtt : rtc.c| netutils|
| RTC_SYNC_USING_NTP 选项| 有,在rtt中的 rtc.c| 无(希望加上)|

-----------------------

我的希望:
* 在 `netutils/ntp/ntp.c` 的404行加入`#ifdef RTC_SYNC_USING_NTP`
* 在 `netutils/ntp/ntp.c` 的441行与442行中间插入`#endif /* RTC_SYNC_USING_NTP */`
* netutils 的 Kconfig 加入 `RTC_SYNC_USING_NTP` ,象原来 RTT 4.03 的一样,现在已master 中删除掉的

```c
//netutils/ntp/ntp.c

#ifdef RTC_SYNC_USING_NTP    // <--- 404行,新插入的
static void ntp_sync_thread_enrty(void *param)
{
    /* first sync delay for network connect */
    rt_thread_delay(RTC_NTP_FIRST_SYNC_DELAY * RT_TICK_PER_SECOND);

    while (1)
    {
        ntp_sync_to_rtc(NULL);
        rt_thread_delay(RTC_NTP_SYNC_PERIOD * RT_TICK_PER_SECOND);
    }
}

static int rt_rtc_ntp_sync_init(void)
{
    static rt_bool_t init_ok = RT_FALSE;
    rt_thread_t thread;

    if (init_ok)
    {
        return 0;
    }

    thread = rt_thread_create("ntp_sync", ntp_sync_thread_enrty, RT_NULL, 1300, RT_THREAD_PRIORITY_MAX - 2, 20);
    if (thread)
    {
        rt_thread_startup(thread);
    }
    else
    {
        return -RT_ENOMEM;
    }

    init_ok = RT_TRUE;

    return RT_EOK;
}
INIT_COMPONENT_EXPORT(rt_rtc_ntp_sync_init);
#endif /* RTC_SYNC_USING_NTP */    // <---新插入的
#endif   //<-- 原 442 行

```

**Comment by mysterywolf** [comment]
哦 我明白你啥意思了 你是想可以取消自动同步功能 手动同步

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/netutils/pull/63

**Comment by dongly** [comment]
对,谢谢

**Comment by mysterywolf** [comment]
加上了

**Comment by mysterywolf** [comment]
这个issue可以关了
