### ISSUE TITLE
RTT master 最新版配netutils V1.2 ,NTP获取的时间超前8小时

### ISSUE THREAD

**Issue by dongly** [RT-Thread-packages/netutils#64]
* RT-Thread 版本: master  (5ba96109c60c4b1a)
* netutils 版本: V1.2
* 现象: 通过NTP 获取时间,会超前8小时.(如: 当前时间为0:00,则获取到的时间为8:00)

**Comment by mysterywolf** [comment]
请使用v1.3及以后的版本

**Comment by armink** [comment]
理论上 master 的 RTT 没法选择 V1.2 的 NTP 的

**Comment by mysterywolf** [comment]
我加个if

**Comment by mysterywolf** [comment]
这个issue可以关了
