### ISSUE TITLE
新版本的 NTP 同步无法同步日期只能同步时间

### ISSUE THREAD

**Issue by majianjia** [RT-Thread-packages/netutils#69]
涉及到这次改动：https://github.com/RT-Thread-packages/netutils/commit/1e02f876dc926efe3535eeeb4a61ab750231f9ef#

源文件377行设置date和time分别用了两次localtime. 新版删掉后导致NTP 同步**无法同步日期**只能**同步时间**。

单步调试发现，先进行set_time的情况下，set_time之后，日期被重置，时间保留。
我现在先设置日期，再设置时间，可以同步日期并且同步时间。

获取时间正确。
![image](https://user-images.githubusercontent.com/3821068/119243028-30330480-bb5b-11eb-8a36-7744c679c269.png)
年月被重置成RTC原先的时间。
![image](https://user-images.githubusercontent.com/3821068/119243044-3d4ff380-bb5b-11eb-9915-415e36cbae61.png)

这个问题可能跟底层RTC驱动有关。
STM32L476

**Comment by mysterywolf** [comment]
这个应该是底层的问题 https://github.com/RT-Thread/rt-thread/issues/4627
新版的NTP同步的不是日期或者时间，只同步UNI时间戳，这个东西是包含着日期和事件的，如果数据装订不进去，说明底层有问题了；此前我已经察觉到了drv_rtc.c有问题，有论坛的人反应过这个问题。

**Comment by mysterywolf** [comment]
能考虑给rt-thread master 提个pr吗 我对HAL库不太熟悉

**Comment by majianjia** [comment]
> 
> 
> 能考虑给rt-thread master 提个pr吗 我对HAL库不太熟悉

我也不太熟悉，我有空的话看看。

**Comment by majianjia** [comment]
已修复
