### ISSUE TITLE
使用ec20网卡进行ntp同步只能与第一个服务器进行时间同步

### ISSUE THREAD

**Issue by baiqiudi** [RT-Thread-packages/netutils#94]
查看代码并使用AT调试发现，虽然设置了三个NTP服务器但是在socket连接的时候只与第一个服务器建立了UDP连接，之后的两个还使用的第一个连接，导致三次同步实际都与第一个服务器进行，但是使用w5500抓包发现是单独与每个服务器进行的连接。
建立连接的地方（会分别向每个服务器发送同步请求，只有第一次建立连接）：
![image](https://github.com/RT-Thread-packages/netutils/assets/44767926/606320ae-ce69-4646-be03-bf85758ab730)
代码最后才关闭socket(一次操作):
![image](https://github.com/RT-Thread-packages/netutils/assets/44767926/0c0813fb-eb55-4e9d-9287-95d24a5899dc)

**Comment by yangpengya** [comment]
最新主线已修复[https://github.com/RT-Thread/rt-thread/pull/9403](url)
